# Generated by Django 3.2.25 on 2024-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcount',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tagcount',
            name='tag',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='tagcount',
            index=models.Index(condition=models.Q(('count__gt', 10)), fields=['tag'], name='tag_count_idx'),
        ),
    ]
